### ISSUE TITLE
Prevent modal from being closed while http request is active

### ISSUE THREAD

**Issue by FreezinG117** [meanie/angular-modal#1]
Hey! I've been using angular-modal for a while now.

I wanted a way to cancel the closing event or simply an option to change _closeOnEsc_, _closeOnClick_ while the modal is open.

I don't think this is already implemented

**Comment by adambuczynski** [comment]
Hi @FreezinG117 , do you mean that you want to change what's happening for the `closeOnEsc` or `closeOnClick` events? Would a hook like `onBeforeClose` when you can cancel the close event help?

**Comment by FreezinG117** [comment]
Yes, I think that would work.

**Comment by adambuczynski** [comment]
Implemented in 1.3.0
Simply add the following function to your configuration:

```javascript
onBeforeClose: function(modalInstance, result, wasDismissed) {

  //Return true or nothing at all to allow closing of the modal
  return true;

  //Return anything else to prevent closing the modal.
  //The value you return will be used as the reject reason for the close promise.
  return 'invalid';
}
```

**Comment by adambuczynski** [comment]
@FreezinG117 Let me know if there's anything else you feel would be useful to add!

**Comment by FreezinG117** [comment]
Just tested. Works fine ;)

Hum, I can't think of anything else right now but I'll be sure to let you know if I remember something else.
