### ISSUE TITLE
Could you provide it as bower module?

### ISSUE THREAD

**Issue by robsonrosa** [meanie/angular-modal#3]
Could you provide it as bower module?

**Comment by adamreisnz** [comment]
Hi, in short -- sorry, no! :smile:

I've done this in the past, but I don't feel Bower is necessary or useful anymore, and I don't want to have to maintain the package on two package repositories.

You can simply use npm (or yarn) instead, which I feel is a much better alternative to Bower.

**Comment by robsonrosa** [comment]
Well, unfortunately I have no options but using Bower because of internal requirements. :(
Thanks again.

**Comment by adamreisnz** [comment]
Ok, well you could always fork this repo and create a bower module based on that. I'd be fine with that if you are willing to manage it and credit this original repository.
